images: Unbreak the tests for Fedora 37
The Korean translations for the psmisc manuals were only added in psmisc
23.6 [1], while Fedora 37 has psmisc 23.4.  This led to:
  STEP 16/20: RUN rm /extra-packages
  STEP 17/20: COPY ensure-files /
  STEP 18/20: RUN ret_val=0;   while read file; do     if ! compgen ...
  /usr/share/man/ko/man1/pstree.1*: No such file or directory
  Error: building at STEP "RUN ret_val=0;   while read file; do...":
    while running runtime: exit status 1

Fallout from e41d920dd9a847cc7a5cc809a86d9ba98bdd88d0

[1] psmisc commit 3098e641dc1ddb21
    https://gitlab.com/psmisc/psmisc/-/commit/3098e641dc1ddb21

[2] https://src.fedoraproject.org/rpms/psmisc/tree/f37

https://github.com/containers/toolbox/pull/1394