cmd/initContainer: Detect mount points when creating symbolic links
An error like this shouldn't happen unless Podman did something
unexpected or was used wrong or something else happened that inserted an
unexpected mount point in the container to surprise the entry point.
eg., removing the --no-hosts option from 'podman create' will trigger
this.

This change replaces the more generic error message:
  $ toolbox enter
  Error: failed to redirect /etc/hosts to /run/host/etc/hosts: remove
      /etc/hosts: device or resource busy

... to something more precise:
  $ toolbox enter
  Error: failed to redirect /etc/hosts to /run/host/etc/hosts:
      /etc/hosts is a mount point

https://github.com/containers/toolbox/pull/1692