cmd/initContainer: Remove path on redirection when it exists
The redirectPath() function does not work correctly if containerPath
does not exist (like /media). The error message often looks like this:

Error: failed to redirect /media to /run/media: remove /media: no such file or directory

This makes redirectPath try to remove containerPath only if it exists.
The existence of containerPath is done using utils.PathExist().

https://github.com/containers/toolbox/pull/556