pkg/term, pkg/utils: Stop the test functions if they fail their set-up
Currently, if for some reason the set-up steps of a test function fails,
like opening /dev/ptmx, it continues to run and encounters subsequent
failures:
  --- FAIL: TestIsTerminalTerminal (0.00s)
      term_test.go:41:
                  Error Trace: toolbox/src/pkg/term/term_test.go:41
                  Error:       Received unexpected error:
                               open /dev/ptmx: not a directory
                  Test:        TestIsTerminalTerminal
      term_test.go:45:
                  Error Trace: toolbox/src/pkg/term/term_test.go:45
                  Error:       Should be true
                  Test:	       TestIsTerminalTerminal
  FAIL
  FAIL  github.com/containers/toolbox/pkg/term  0.004s

The test functions are only meaningful if the set-up succeeds, and
continuing in the case of a failure only leads to noise.  Therefore,
stop executing them if they fail their set-up.

This changes the previous failure to:
  --- FAIL: TestIsTerminalTerminal (0.00s)
      term_test.go:42:
                  Error Trace: toolbox/src/pkg/term/term_test.go:42
                  Error:       Received unexpected error:
                               open /dev/ptmx: not a directory
                  Test:        TestIsTerminalTerminal
  FAIL
  FAIL  github.com/containers/toolbox/pkg/term  0.003s

Fallout from the following:
  * 3d5499366aa18ad676ae31698f0d1a4f9f1ce35b
  * aca4e9dd2626dcd2e822b311712c27ea5bd0a22a
  * e9e77fb0696f2d6f375798b6752008edf1f4762a

https://github.com/containers/toolbox/pull/1727