Do not mount /run/media when missing
This change prevents this exception:
Error: error checking path "/run/media": stat /run/media: no such file or directory