cmd/initContainer: Unbreak 'enter' if NVIDIA Persistence Daemon is used
If the NVIDIA Persistence Daemon is used, then 'enter' fails with:
  $ sudo systemctl start nvidia-persistenced.service
  $ toolbox enter
  Error: mount: /run/nvidia-persistenced/socket: mount point does not exist.
         dmesg(1) may have more information after failed mount system call.
  failed to apply mount from Container Device Interface for NVIDIA

This is due to the socket at /run/nvidia-persistenced/socket being
listed in the Container Device Interface specification when the NVIDIA
Persistence Daemon is used.

Fallout from 6e848b250b4cde98fb9a40b17421f1f54eacd8f3

https://github.com/containers/toolbox/issues/1572